name: 01-2 - Integration - SONARQUBE

on:
  workflow

jobs:
  QualityBack:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      -name: SonarQube Scan
       uses: QonarSource/sonarcloud-github-action@v3.1.0
       with:
        projectBaseDir: ./Backend
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
  QualityFront:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      -name: SonarQube Scan
       uses: QonarSource/sonarcloud-github-action@v3.1.0
       with:
        projectBaseDir: ./frontend
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}